name: "Build master"
on:
  push:
    branches: [ 'master' ]
    paths-ignore:
      - 'msvc*/**'
      - 'check/**'
      - 'doc/**'
      - 'packaging/**'
      - 'snap/**'
      - '*.md'
      - 'check/**'
      - 'default/**'
      - 'test-scripting/**'
      - '.github/ISSUE_TEMPLATE/**'
      - "pyproject.toml"
jobs:
  android:
    uses: ./.github/workflows/_build-android.yml
  macos:
    strategy:
      matrix:
        os: [ macos-11, macos-12, macos-13 ]
    uses: ./.github/workflows/_build-macos.yml
    with:
      os: ${{ matrix.os }}
  ubuntu:
    uses: ./.github/workflows/_build-ubuntu.yml
  windows:
    uses: ./.github/workflows/_build-windows.yml
  windows-msvc:
    uses: ./.github/workflows/_build-windows-msvs.yml
  docker:
    uses: ./.github/workflows/_build-docker.yml
  snapcraft:
    uses: ./.github/workflows/_build_snapcraft.yml
  discord-notify-failure:
    - uses: sarisia/actions-status-discord@v1
      needs:
        - android
        - macos
        - ubuntu
        - windows
        - docker
        - snapcraft
      if: failure()
      with:
        title: 'FreeOrion build master'
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        color: 0xff0000
        username: 'FreeOrion Repo'
        url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        avatar_url: https://github.githubassets.com/images/modules/logos_page/Octocat.png
