name: "Windows build"

on: workflow_dispatch

jobs:
  build-windows-2022-cmake:
    name: MSVS 2022 on Windows
    runs-on: windows-2022
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Download SDK
        id: download-sdk
        uses: suisei-cn/actions-download-file@v1
        with:
          url: https://github.com/freeorion/freeorion-sdk/releases/download/v12/FreeOrionSDK_12_MSVC-v141-Win32.zip
          target: ../
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.3
        with:
            vs-prerelease: true
      - name: Configure
        run: |
          unzip -q ../${{ steps.download-sdk.outputs.filename }} -d ..
          mkdir build
          pushd build
          cmake -G "Visual Studio 17 2022" -T v143 -A Win32 -DBUILD_TESTING=On -DBUILD_CLIENT_GODOT=On -DCMAKE_C_FLAGS=/MP -DCMAKE_CXX_FLAGS=/MP ..
      - name: Build
        run: |
          pushd build
          cmake --build . --config "Release" -- /maxcpucount /property:BuildInParallel=true /property:CL_MPCount=2 /verbosity:minimal
      - name: Test
        run: |
          pushd build
          $env:Path += ";$($pwd.Path)\\Release"
          cmake --build . --config "Release" --target unittest
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: build/
          retention-days: 5
